- name: Add the newly created EC2 instance(s) to /etc/hosts
  local_action:
    module: lineinfile
    dest: "artifacts/etchosts"
    create: yes
    insertafter: EOF
    line: "{{ item.public_ip_address }} {{ item.tags.L1Ptype }}{{ item.ami_launch_index|int + 1 }}"
  with_items: "{{ ec2instances.instances }}"

- name: Setup known_hosts
  shell: /usr/bin/ssh-keyscan {{ item.public_ip_address }} >> ~/.ssh/known_hosts
  with_items:  "{{ ec2instances.instances }}"


