#- include: plays/build_inventory.yml
#  tags: always

- name: Provision environment
  hosts: localhost
  connection: local
  vars:
    app_ingress_rules:
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
    env_path_loc: env

# Save for later when we can start using our own FQDN instead of EC2 ips/dns
#  pre_tasks:
#    - name: Add DNS zone
#      route53_zone:
#        zone: '{{ env_domain }}'
#        state: present
#      tags: dns
  roles:

    - role: artifacts_azure
      tags: always

#- name: Provision management node
#  hosts: mgmt
#  tags: provision2, mgmt
#  roles:
#    - { role: provision_ec2_mgmt, become: yes }
#    - { role: provision_ec2_mgmt_nr, become: no }

- name: Provision worker node(s)
  hosts: localhost
  tags: provision2, workers
  roles:
    - { role: provision_azure, become: yes }

- name: Login to docker
  hosts: localhost
  tags: always
  roles:
    - role: login_docker

- name:  Install DFSP components
  hosts: localhost
  tags: dfsp
  roles:
    - role: dfsp
      env_path: env/{{ env }}
      log_ip: 172.17.0.1
      api_hostname: '{{ ansible_host }}'

- name: Pull ModusBox components
  hosts: localhost
  tags: mule
  become: yes
  roles:
    - role: mule_non_docker_pre

- name: Install ModusBox components
  hosts: localhost
  tags: mule
  become: yes
  roles:
#    - role: mule
    - role: mule_non_docker
      env_path: env/{{ env }}
      log_ip: localhost
      sandbox_host: '{{ ansible_host }}'
      mgmt_host: '{{ mgmt_host }}'

- name:  Pause for other DFSP to be installed before running user data
  hosts: localhost
  roles:
    - role: pause

#- name:  Install Account and User Data
#  hosts: mgmt
#  tags: request
#  roles:
#    - role: request_data_azure

- name:  Install ILP components
  hosts: localhost
  tags: ilp
  roles:
    - role: ilp
      env_path: env/{{ env }}
      log_ip: 172.17.0.1
      ist_host_name: '{{ ist_host }}'
      ilp_host_name: '{{ ansible_host }}'
      ilp_base_url: 'http://{{ ansible_host }}'
      ilp_address_neighborhood: 'levelone'
      ilp_central_ledger_prefix: "levelone.ist."

#- name:  Install ELK stack
#  hosts: mgmt
#  tags: elk
#  roles:
#    - { role: elk, become: yes, mgmt_host: '{{ hostvars.mgmt1.ec2_facts.public_dns_name }}' }
#
#- name: Install Filebeat
#  hosts: dfsps, ists
#  tags: filebeat
#  roles:
#    - { role: filebeat, become: yes, mgmt_host: '{{ hostvars.mgmt1.ec2_facts.public_dns_name }}' }
#
#- name: Install Curator
#  hosts: mgmt
#  tags: curator
#  roles:
#    - { role: curator, become: yes, mgmt_host: '{{ hostvars.mgmt1.ec2_facts.public_dns_name }}' }

- name: Remove temporary artifact files
  hosts: localhost
  tags: cleanup
  roles:
    - role: clean_artifacts