---
    - name: Add Java 8 repository
      become: true
      apt_repository:
        repo: 'ppa:openjdk-r/ppa'
        state: present

    - name: Install Java components
      become: true
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - openjdk-8-jre

    - name: Get Elasticsearch package
      become: yes
      get_url:
        url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.3.deb
        dest: ~/elasticsearch-5.4.3.deb

    - name: Install Elasticsearch
      become: yes
      apt:
        deb: ~/elasticsearch-5.4.3.deb

    - name: Configure Elasticsearch
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        insertafter: '^#network.host: 192.168.0.1'
        line: 'network.host: [_eth0_,_local_]'

# Do more research on this...looks like log4j is setup.
#    - copy:
#        src: artifacts/logging.yml
#        dest: /etc/elasticsearch/

    - name: Restart Elasticsearch
      service:
        name: elasticsearch
        state:  restarted

    - name: Download Kibana
      get_url:
        url: https://artifacts.elastic.co/downloads/kibana/kibana-5.4.3-amd64.deb
        dest: ~/kibana-5.4.3-amd64.deb

    - name: Install Kibana
      become: yes
      apt:
        deb: ~/kibana-5.4.3-amd64.deb

    - name: Configure Kibana
      replace:
        path: /etc/kibana/kibana.yml
        regexp: '^#server.port: 5601'
        replace: 'server.port: 5601'

    - replace:
        path: /etc/kibana/kibana.yml
        regexp: '^#server.name: "your-hostname"'
        replace: 'server.name: "{{ inventory_hostname }}-{{ name_tag }}"'

#  Using localhost for now out for now as we are using all of elk on the same host
    - replace:
        path: /etc/kibana/kibana.yml
        regexp: '^#server.host: "localhost"'
        replace: 'server.host: "localhost"'
        #replace: 'server.host: "{{ hostvars[inventory_hostname].ansible_host }}"'

    - replace:
        path: /etc/kibana/kibana.yml
        regexp: '#elasticsearch.url: "http://localhost:9200"'
        replace: 'elasticsearch.url: "http://localhost:9200"'

    - copy:
        src: artifacts/kibana
        dest: /etc/logrotate.d/

    - name: Restart Kibana
      service:
        name: kibana
        state:  restarted

    # Pre-create the nginx account and also install apache2-utils for htpasswd
    - name: Pre-install nginx user
      #shell: sudo adduser --system --no-create-home --shell /bin/false --group --disabled-login nginx
      become: yes
      user:
        name: nginx
        comment: "Nginx User"
        createhome: no
        system: yes
        shell: /bin/false

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Setup the Kibana user in NGINX
      htpasswd:
        path: /etc/nginx/htpasswd.users
        name: "{{ kibana_user }}"
        password: "{{ kibana_pass }}"
        state: present

    - name: Copy NGINX config files over to the server
      copy:
        src: artifacts/kibana.conf
        dest: /etc/nginx/conf.d/

    - copy:
        src: artifacts/nginx.conf
        dest: /etc/nginx/

    - copy:
        src: artifacts/nginx
        dest: /etc/logrotate.d/

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

    - name:  Install Logstash
      get_url:
        url: https://artifacts.elastic.co/downloads/logstash/logstash-5.4.3.deb
        dest: ~/logstash-5.4.3.deb

    - apt:
        deb: ~/logstash-5.4.3.deb

    - name: Configure Logstash
      copy:
        src: artifacts/log-pipeline.conf
        dest: /etc/logstash/conf.d

    - copy:
        src: artifacts/logstash
        dest: /etc/logrotate.d/

    - name: Restart Logstash
      service:
        name: logstash
        state: restarted
    
    - name:  Install Metricbeat
      get_url: 
        url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-5.4.3-amd64.deb
        dest: ~/metricbeat-5.4.3-amd64.deb

    - apt:
        deb: ~/metricbeat-5.4.3-amd64.deb

    - name: Restart Metricbeat
      service:
        name: metricbeat
        state:  restarted
    
    - name:  Install Heartbeat
      get_url: 
        url: https://artifacts.elastic.co/downloads/beats/heartbeat/heartbeat-5.4.3-amd64.deb
        dest: ~/heartbeat-5.4.3-amd64.deb

    - apt:
        deb: ~/heartbeat-5.4.3-amd64.deb

    - name: Restart Heartbeat
      service:
        name: heartbeat
        state:  restarted
