- name: Configure Mule-l1p.properties files
  local_action:
    module: blockinfile
    create: yes
    dest: "artifacts/mule_artifacts/conf/mule-l1p.properties.1"
    block: |
      dfsp-host={{ dfsp1_host }}
      ilp-host={{ dfsp1_host }}
      central-dir-env=mock
      proxy-host={{ dfsp1_host }}
      central-dir-host={{ ist_host }}
      central-dir-api.port=3000
      central-fraud-sharing-host={{ ist_host }}
      central-fraud-sharing-api.port=3003
      mock-central-dir.host={{ ist_host }}
      mock-central-dir.port=8088
      metrics.reporter.kafka.broker={{ metrics_host_port }}
      environment=dfsp1-test
      metrics.reporter.environment=dfsp1-{{ name_tag }}
      maxHttpThreadsActive=16
      maxHttpThreadsIdle=4

- local_action:
    module: blockinfile
    create: yes
    dest: "artifacts/mule_artifacts/conf/mule-l1p.properties.2"
    block: |
      dfsp-host={{ dfsp2_host }}
      ilp-host={{ dfsp2_host }}
      central-dir-env=mock
      proxy-host={{ dfsp2_host }}
      central-dir-host={{ ist_host }}
      central-dir-api.port=3000
      central-fraud-sharing-host={{ ist_host }}
      central-fraud-sharing-api.port=3003
      mock-central-dir.host={{ ist_host }}
      mock-central-dir.port=8088
      metrics.reporter.kafka.broker={{ metrics_host_port }}
      environment=dfsp2-test
      metrics.reporter.environment=dfsp2-{{ name_tag }}
      maxHttpThreadsActive=16
      maxHttpThreadsIdle=4

- local_action:
    module: blockinfile
    create: yes
    dest: "artifacts/mule_artifacts/conf_ist/mule-l1p.properties.ist"
    block: |
      central-dir-env=mock
      mock-central-dir.host={{ ist_host }}
      mock-central-dir.port=8088
      metrics.reporter.kafka.broker={{ mgmt_host }}:9092
      environment=ist1-test
      metrics.reporter.environment=ist1-{{ name_tag }}
      maxHttpThreadsActive=16
      maxHttpThreadsIdle=4

- name: Configure adapter-mapping.properties
  local_action:
    module: blockinfile
    create: yes
    dest: "artifacts/mule_artifacts/conf/adapter-mapping.properties.1"
    block: |
      mapping-dfsp-host={{ dfsp1_host }}
      mapping-proxy-host={{ dfsp1_host }}

- local_action:
    module: blockinfile
    create: yes
    dest: "artifacts/mule_artifacts/conf/adapter-mapping.properties.2"
    block: |
      mapping-dfsp-host={{ dfsp2_host }}
      mapping-proxy-host={{ dfsp2_host }}

#- name: Add the newly created EC2 instance(s) to /etc/hosts
#  local_action:
#    module: lineinfile
#    dest: "artifacts/etchosts"
#    create: yes
#    insertafter: EOF
#    line: "{{ item.public_ip_address }} {{ item.tags.L1Ptype }}{{ item.ami_launch_index|int + 1 }}"
#  with_items: "{{ ec2instances.instances }}"
#
#- name: Setup known_hosts
#  shell: /usr/bin/ssh-keyscan {{ item.public_ip_address }} >> ~/.ssh/known_hosts
#  with_items:  "{{ ec2instances.instances }}"


