# Ansible playbook for deploying the
# ilp-connector, ilp-spsp-client-rest, and ilp-spsp-server
# to the L1P test integration environment

# Note this must be run with the CLI param --extra-vars="docker_username=... docker_password=... docker_email=..."
---

- include_vars:
    file: versions/{{ env }}/modusboxversions.yml

- name: start postgres
  docker_container:
    name: postgres-interop
    image: postgres:9.6.5
    env:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      SERVICE_5432_NAME: 'postgres'
    ports: 8102:5432
    restart_policy: always

- name: Waiting to make sure postgres is started
  wait_for:
    port: 8102
    delay: 10

- postgresql_db:
    login_host: '{{ worker_host }}'
    port: 8102
    login_user: postgres
    login_password: postgres
    name: mojaloop
    encoding: UTF-8

- postgresql_user:
    login_host: '{{ worker_host }}'
    port: 8102
    login_user: postgres
    login_password: postgres
    db: mojaloop
    name: mojaloop
    password: 0f44a46921c79f9e179e9947f5fb6bf3
    encrypted: yes

- postgresql_schema:
    login_host: '{{ worker_host }}'
    port: 8102
    login_user: postgres
    login_password: postgres
    name: switch
    database: mojaloop
    owner: mojaloop

#- name: Run psql
#  shell: create_table_switch.participant_fsp_mapping.sh
#  register: result
#  changed_when: "'Table created' in result.stdout"

- name: Start interop-routing
  become: true
  docker_container:
    name: interop-routing
    image: "mojaloop/interop-routing:{{ v_interop_routing }}"
    restart_policy: always
    state: started
    restart: yes
    log_driver: syslog
    log_options:
      syslog-address: 'tcp://{{ log_ip }}:514'
      syslog-facility: daemon
      tag: interop-routing
    ports:
      - "8088:8088"
    env:
      SERVICE_8088_NAME: 'interop-routing'
      MAX_JVM_MEMORY: '256'
      ROUTING_SERVICE_HOST: '0.0.0.0'
      ROUTING_SERVICE_PORT: '8088'
      SWITCH_SERVICE_HOST: '0.0.0.0'
      SWITCH_SERVICE_PORT: '8089'
      ACCOUNT_LOOKUP_SERVICE_HOST: '0.0.0.0'
      ACCOUNT_LOOKUP_SERVICE_PORT: '8090'

- name: Start interop-switch
  become: true
  docker_container:
    name: interop-switch
    image: "mojaloop/interop-switch:{{ v_interop_switch }}"
    restart_policy: always
    state: started
    networks:
      - name: MOJALOOP_NET
    restart: yes
    log_driver: syslog
    log_options:
      syslog-address: 'tcp://{{ log_ip }}:514'
      syslog-facility: daemon
      tag: interop-switch
    ports:
      - "8089:8088"
    env:
      SERVICE_8088_NAME: 'interop-switch'
      MAX_JVM_MEMORY: '256'
      SWITCH_SERVICE_HOST: '0.0.0.0'
      SWITCH_SERVICE_PORT: '8089'
      ACCOUNT_LOOKUP_SERVICE_HOST: '0.0.0.0'
      ACCOUNT_LOOKUP_SERVICE_PORT: '9000'

- name: Start interop-account-lookup
  become: true
  docker_container:
    name: interop-account-lookup
    image: "mojaloop/interop-account-lookup:{{ v_interop_account_lookup }}"
    restart_policy: always
    state: started
    networks:
      - name: MOJALOOP_NET
    restart: yes
    log_driver: syslog
    log_options:
      syslog-address: 'tcp://{{ log_ip }}:514'
      syslog-facility: daemon
      tag: interop-account-lookup
    ports:
      - "8090:8088"
    env:
      SERVICE_8088_NAME: 'interop-account-lookup'
      MAX_JVM_MEMORY: '256'
      SWITCH_SERVICE_HOST: '0.0.0.0'
      SWITCH_SERVICE_PORT: '9000'
      PSQL_HOST: 'localhost'
      PSQL_PORT: '8102'

