# Ansible playbook for deploying the
# ilp-connector, ilp-spsp-client-rest, and ilp-spsp-server
# to the L1P test integration environment

# Note this must be run with the CLI param --extra-vars="docker_username=... docker_password=... docker_email=..."
---
#  - debug:
#      var: {{ inventory_hostname | regex_replace('dfsp') }}
  - include_vars:
      file: versions/{{ env }}/modusboxversions.yml

  - name: Pull interop-domain from Jfrog
    get_url:
      url: https://modusbox.jfrog.io/modusbox/libs-release/com/l1p/interop/interop-domain/{{ v_interop_domain }}/interop-domain-{{ v_interop_domain }}.zip
      dest: artifacts/mule_artifacts/domains/interop-domain.zip
      url_username: "{{ mule_repo_user }}"
      url_password: "{{ mule_repo_pass }}"
    delegate_to: localhost

  - name: Pull interop-scheme-adapter from Jfrog
    get_url:
      url: https://modusbox.jfrog.io/modusbox/libs-release/com/l1p/interop/interop-scheme-adapter/{{ v_interop_scheme_adapter }}/interop-scheme-adapter-{{ v_interop_scheme_adapter }}.zip
      dest: artifacts/mule_artifacts/apps/interop-scheme-adapter-{{ v_interop_scheme_adapter }}.zip
      url_username: "{{ mule_repo_user }}"
      url_password: "{{ mule_repo_pass }}"
    delegate_to: localhost

  - name: Pull interop-dfsp-directory from Jfrog
    get_url:
      url: https://modusbox.jfrog.io/modusbox/libs-release/com/l1p/interop/dfsp/interop-dfsp-directory/{{ v_interop_dfsp_directory }}/interop-dfsp-directory-{{ v_interop_dfsp_directory }}.zip
      dest: artifacts/mule_artifacts/apps/interop-dfsp-directory-{{ v_interop_dfsp_directory }}.zip
      url_username: "{{ mule_repo_user }}"
      url_password: "{{ mule_repo_pass }}"
    delegate_to: localhost

  - name: Pull interop-ilp-ledger from Jfrog
    get_url:
      url: https://modusbox.jfrog.io/modusbox/libs-release/com/l1p/interop/ilp/interop-ilp-ledger/{{ v_interop_ilp_ledger }}/interop-ilp-ledger-{{ v_interop_ilp_ledger }}.zip
      dest: artifacts/mule_artifacts/apps/interop-ilp-ledger-{{ v_interop_ilp_ledger }}.zip
      url_username: "{{ mule_repo_user }}"
      url_password: "{{ mule_repo_pass }}"
    delegate_to: localhost

  - local_action:
      module: archive
      path:
        - artifacts/deploy
        - artifacts/requests
        - artifacts/mule_artifacts
        - artifacts/bulk
      dest: ./mule.gz
